### ISSUE TITLE
Develop mock software for Motor Movement, Temperature reading, and pH reading| Due Jan 27

### ISSUE THREAD

**Issue by SJeffries19** [Baileywyan/WSUTeamProjects2#3]
Please find and develop the appropriate python code for our project. (motor movement, temperature reading, etc.)

**Comment by SJeffries19** [comment]
# Motor movement code

import vexiq
import sys

motor_arm = vexiq.Motor(6)

motor_arm.run(20)
sys.sleep(3)
motor_arm.off()

**Comment by SJeffries19** [comment]
### Thermometer code
import time
from w1thermsensor import W1ThermSensor
sensor = W1ThermSensor()

while True:
    temperature = sensor.get_temperature()
    print("The temperature is %s celsius" % temperature)
    time.sleep(1)

**Comment by SJeffries19** [comment]
### pH Code

import datetime as dt
import time
import board
import busio
from anyleaf import PhSensor, OnBoard

LOOP_DELAY = 60 * 5  # Time to sleep, in seconds.
LOG_FILENAME = "ph_readings.csv"


def main():
    i2c = busio.I2C(board.SCL, board.SDA)
    ph_sensor = PhSensor(i2c, LOOP_DELAY)

    while True:
        ph = ph_sensor.read(OnBoard())
        timestamp = dt.datetime.now()

        # Open our log file in append-line mode. This way new lines can be 
        # written without overwriting existing ones.
        with open(LOG_FILENAME, 'a') as f:
            # Write the timestamp to the first column, and pH to the second.
            f.write(f"{timestamp.isoformat()},{round(ph, 2)}\n")

        # Wait for 5 minutes before taking and logging another reading.
        time.sleep(LOOP_DELAY)


if __name__ == "__main__":
    main()

**Comment by Baileywyan** [comment]
[(https://learn.sparkfun.com/tutorials/sparkfun-qwiic-dual-solid-state-relay-hookup-guide/qwiic-relay-python-package)]
[https://learn.sparkfun.com/tutorials/python-programming-tutorial-getting-started-with-the-raspberry-pi]
[https://github.com/sparkfun/Qwiic_Relay_Py]([https://github.com/sparkfun/Qwiic_Relay_Py]) github 
[https://content.instructables.com/FRU/KW61/J9YJGOWQ/FRUKW61J9YJGOWQ.py] link to code here
import RPi.GPIO as GPIO
import time

channel = 21

# GPIO setup
GPIO.setmode(GPIO.BCM)
GPIO.setup(channel, GPIO.OUT)

def motor_on(pin):
    GPIO.output(pin, GPIO.HIGH)  # Turn motor on


def motor_off(pin):
    GPIO.output(pin, GPIO.LOW)  # Turn motor off


if __name__ == '__main__':
    try:
        motor_on(channel)
        time.sleep(1)
        motor_off(channel)
        time.sleep(1)
        GPIO.cleanup()
    except KeyboardInterrupt:
        GPIO.cleanup()
