### ISSUE TITLE
Draft the web application prototype | Due Jan 27

### ISSUE THREAD

**Issue by Baileywyan** [Baileywyan/WSUTeamProjects2#6]

**Comment by SJeffries19** [comment]
Assigned to Kelly

**Comment by kelly-nh** [comment]
1. [Website app Mockup](https://www.canva.com/design/DAFYlXmYRQM/qY8eC4T89mzNlIrdtUarxA/view?utm_content=DAFYlXmYRQM&utm_campaign=designshare&utm_medium=link&utm_source=publishsharelink)

2. [Mobile app Mockup](https://www.canva.com/design/DAFYxRpZkD4/jEhuWjvBFLBoC_-4I6tqjg/view?utm_content=DAFYxRpZkD4&utm_campaign=designshare&utm_medium=link&utm_source=publishsharelink)
